stars
mate-academy/layout_stars pull request #1199
Opened 2022-04-16 18:35 UTC by p-omogit-e

- [DEMO LINK](https://p-omogit-e.github.io/layout_stars/)
- [TEST REPORT LINK](https://p-omogit-e.github.io/layout_stars/report/html_report/)

2022-04-18 11:47 UTC, ArtemTopolskyi requested changes

2022-04-18 11:47 UTC, ArtemTopolskyi commented on src/index.html
> +        <div class="star--grey"></div>
в этом задании не нужно разделять звезды на yellow и grey в html коде, это нужно делать в css. В html у всех элементов должен просто быть класс star и все

2022-04-18 11:47 UTC, ArtemTopolskyi commented on src/style.css
> +}
используй общие классы для всех звезд. С помощью stars--(number) nth-child можно изменять их background image

2022-04-26 16:54 UTC, ArturErmolenko approved these changes

2025-12-17 21:24 UTC, closed without merging