Stars v01
mate-academy/layout_stars pull request #1261
Opened 2022-05-06 17:40 UTC by leonid-levtseniuk

2022-05-10 17:11 UTC, vkryvytskyy requested changes

2022-05-10 17:11 UTC, vkryvytskyy commented on src/index.html
> +        >
Не надо картинки добавлять в html, тут должы быть div или span теги, которым через css на бекграунд устанавливается нужная картинка

2022-05-10 17:11 UTC, vkryvytskyy commented on src/style.css
> +}
Эти все стили одинаковые, уверен есть способо не писать ожно и то же 6 раз

2022-05-10 17:11 UTC, vkryvytskyy commented on src/style.css
> +  flex-direction: row;
Это стандартное значение свойства flex-direction

2022-05-15 15:40 UTC, leonid-levtseniuk commented
Там прилетіло мільйон комітів, оскільки в мене не виходило запушити і я якось з тим розбирався, соррі

2022-05-17 08:52 UTC, ArtemTopolskyi requested changes

2022-05-17 08:57 UTC, Bohdan-Maksymiuk requested changes
run deploy - demo links don't work

2022-05-17 08:57 UTC, Bohdan-Maksymiuk commented on src/index.html
> +      <div class="stars--0"></div>
```suggestion
      <div class="stars stars--0">
        <div class="stars__star"></div>
        <div class="stars__star"></div>
        <div class="stars__star"></div>
        <div class="stars__star"></div>
        <div class="stars__star"></div>
      </div>
```

2022-05-17 08:57 UTC, Bohdan-Maksymiuk commented on src/index.html
> +      <div class="stars--0"></div>
it should be background image for `.stars__star` which depends on modifier

2022-05-18 14:04 UTC, ArtemTopolskyi requested changes
все остальные стили лишние

2022-05-18 14:04 UTC, ArtemTopolskyi commented on src/style.css
> +}
```suggestion
.stars--1 .card__star:nth-child(-n + 1),
.stars--2 .card__star:nth-child(-n + 2),
.stars--3 .card__star:nth-child(-n + 3),
.stars--4 .card__star:nth-child(-n + 4),
.stars--5 .card__star:nth-child(-n + 5)  {
  background-image: url(/images/star.svg);
}
```

2022-05-18 14:04 UTC, ArtemTopolskyi commented on src/style.css
> +}
в остальных стилях нет необходимости

2022-05-19 09:21 UTC, ArtemTopolskyi requested changes

2022-05-19 13:38 UTC, aliceblunt8 requested changes

2022-05-19 13:38 UTC, aliceblunt8 commented on src/index.html
> +      <div class="card__star"></div>
the name od the block is stars, not card

```suggestion
      <div class="stars__star"></div>
```

2022-05-19 17:54 UTC, closed without merging