layout stars was created
mate-academy/layout_stars pull request #1266
Opened 2022-05-06 21:26 UTC by MariiaNH

- [DEMO LINK](https://mariianh.github.io/layout_stars/)
- [TEST REPORT LINK](https://mariianh.github.io/layout_stars/report/html_report/)

2022-05-06 21:31 UTC, MariiaNH commented
код проходить тест на весь блок (тести на рядки окремо не проходять - та візуально вони співпадають). Переробляла розташування елементів в рядку і через justify-content: space-between і margin-left - ефект однаковий.
 Також при збереженні чомусь файл .bemlintrc.json був Untracked.

2022-05-08 10:52 UTC, Olexandr6 requested changes

2022-05-08 10:52 UTC, Olexandr6 commented on src/style.css
> +  align-items: center;
Delete this
```suggestion
```

2022-05-08 10:52 UTC, Olexandr6 commented on src/style.css
> +}
[Checklist](https://github.com/mate-academy/layout_stars/blob/master/checklist.md) 2nd point

2022-05-09 07:47 UTC, Olexandr6 approved these changes
Much better👍

2022-10-31 09:20 UTC, closed without merging