Initial commit
mate-academy/layout_stars pull request #1337
Opened 2022-05-31 09:45 UTC by Dmytro-Kretov

- [DEMO LINK](https://Dmytro-Kretov.github.io/layout_stars/)
- [TEST REPORT LINK](https://Dmytro-Kretov.github.io/layout_stars/report/html_report/)

2022-06-01 11:59 UTC, aliceblunt8 requested changes

2022-06-01 12:02 UTC, Bohdan-Maksymiuk requested changes
fix vertical centering of stars in rows (you can check tests)

2022-06-03 10:04 UTC, aliceblunt8 approved these changes

2022-06-03 10:04 UTC, aliceblunt8 commented on src/style.css
> +  background-repeat: no-repeat;
```suggestion
```

2023-10-12 11:57 UTC, closed without merging