problem with test report
mate-academy/layout_stars pull request #1343
Opened 2022-06-04 09:20 UTC by pavel-gutsal

https://pavel-gutsal.github.io/layout_stars/
https://pavel-gutsal.github.io/layout_stars/report/html_report/
unfortunatly pixel perfect test fails
me and Artem Topolski tried to resolve this error but we failed .
with his pemission I pushed it on github as it is.
thanks for understanding.

2022-06-06 10:30 UTC, ArturErmolenko requested changes

2022-06-06 10:30 UTC, ArturErmolenko commented on src/style.css
> +  flex-direction: row;
это дефолтное значение его можно не указывать

2022-06-06 10:30 UTC, ArturErmolenko commented on src/style.css
> +}
селекторы с одинаковыми стилями можно записать через запятую 
```
.stars--1 :first-child,
.stars--2 :nth-child(-n + 2),
.stars--3 :nth-child(-n + 3),
.stars--4 :nth-child(-n + 4),
.stars--5 :nth-child(-n + 5) {
   background-image: url("/images/star-active.svg");
 }
```

2022-06-07 16:58 UTC, vkryvytskyy approved these changes

2022-06-07 16:58 UTC, vkryvytskyy commented on src/style.css
> +.stars .stars__star {
```suggestion
.stars__star {
```

2022-06-07 17:41 UTC, pavel-gutsal commented
mentioned issue is fixed

2022-10-07 11:08 UTC, closed without merging