added stars
mate-academy/layout_stars pull request #1548
Opened 2022-07-20 12:20 UTC by dimaus97

- [DEMO LINK](https://dimaus97.github.io/layout_stars/)
- [TEST REPORT LINK](https://dimaus97.github.io/layout_stars/report/html_report/)

2022-07-21 11:29 UTC, marina-tilniak requested changes
тести мають проходити

2022-07-21 11:29 UTC, marina-tilniak commented on src/style.css
> +  background-repeat: no-repeat;
ці стилі уже заданеі для .stars__star не потрібно їх дублювати

2022-07-21 11:29 UTC, marina-tilniak commented on src/style.css
> +.stars--1 .stars__star:first-of-type {
```suggestion
.stars--1 :first-of-type {
```

2022-07-21 11:29 UTC, marina-tilniak commented on src/style.css
> +  background-repeat: no-repeat;
прориши селектори через кому, 
❗ не дублюй стилі

2022-07-28 11:00 UTC, Bohdan-Maksymiuk requested changes

2022-07-28 11:00 UTC, Bohdan-Maksymiuk commented on src/style.css
> +  height: 96px;
remove hardcode
it should be stretched by content

2022-07-28 11:00 UTC, Bohdan-Maksymiuk commented on src/style.css
> +  width: 96px;
same

2022-07-28 11:00 UTC, Bohdan-Maksymiuk commented on src/style.css
> +}
```suggestion
.stars--1 .stars__star:first-of-type,
.stars--2 .stars__star:nth-of-type(-n+2),
.stars--3 .stars__star:nth-of-type(-n+3),
.stars--4 .stars__star:not(:last-of-type),
.stars--5 .stars__star:nth-of-type(n+1) {
  background-image: url(./images/star-active.svg);
  background-position: center;
  background-repeat: no-repeat;
  background-size: auto;
}
```

2022-07-28 11:00 UTC, Bohdan-Maksymiuk commented on src/style.css
> +  background-repeat: no-repeat;
you can add `margin-right: 4px;` (not for last child)

2026-09-02 08:50 UTC, closed without merging