Stars
mate-academy/layout_stars pull request #1550
Opened 2022-07-20 20:08 UTC by Qsery93

2022-07-22 09:04 UTC, valerii-derkach requested changes
please provide demolinks
 and fix comments

2022-07-22 09:04 UTC, valerii-derkach commented on src/index.html
> +      </span>
either
```suggestion
      <span class="stars__star"></span>
```

2022-07-22 09:04 UTC, valerii-derkach commented on src/index.html
> +      </span>
or
```suggestion
      <span
        class="stars__star"
      >
      </span>
```

2022-07-24 09:38 UTC, Qsery93 commented on src/index.html
> +      </span>
- [DEMO LINK](https://Qsery93.github.io/layout_stars/)
- [TEST REPORT LINK](https://Qsery93.github.io/layout_stars/report/html_report/)

2022-07-24 09:47 UTC, Qsery93 commented
- [DEMO LINK](https://Qsery93.github.io/layout_stars/)
- [TEST REPORT LINK](https://Qsery93.github.io/layout_stars/report/html_report/)

>

2022-07-24 09:47 UTC, closed without merging

2022-07-24 09:48 UTC, Qsery93 commented
> please provide demolinks and fix comments

- [DEMO LINK](https://Qsery93.github.io/layout_stars/)
- [TEST REPORT LINK](https://Qsery93.github.io/layout_stars/report/html_report/)