solution
mate-academy/layout_stars pull request #1930
Opened 2022-10-07 13:35 UTC by Sergej161995

[DEMO LINK](https://Sergej161995.github.io/layout_stars/)
 [TEST REPORT LINK](https://Sergej161995.github.io/layout_stars/report/html_report/)

2022-10-08 13:16 UTC, ivanchuk-yurii requested changes

2022-10-08 13:16 UTC, ivanchuk-yurii commented on src/style.css
> +  padding: 0;
apply only for elements you need, not `*` all

2022-10-13 12:36 UTC, marina-tilniak commented on src/index.html
> +    </div>
there shouldn’t be empty line between child and parent element

2022-10-13 12:36 UTC, marina-tilniak commented on src/style.css
> +
```suggestion
  
```

2022-10-13 12:37 UTC, marina-tilniak commented on src/index.html
> +      <div class="stars stars--0">
```suggestion
    <div>
      <div class="stars stars--0">
```

2022-10-15 11:51 UTC, Sergej161995 commented on src/style.css
> +
изменил

2022-10-15 11:53 UTC, TarasHoliuk requested changes
Please, fix previous comments

2022-10-15 11:53 UTC, TarasHoliuk commented on src/index.html
> +      <div class="stars stars--0">
You didn't do suggested changes

2022-10-15 11:53 UTC, TarasHoliuk commented on src/index.html
> +</html>
You didn't add empty line at the end of file - fix it

2022-10-15 12:25 UTC, closed without merging