Initial commit
mate-academy/layout_stars pull request #1956
Opened 2022-10-20 18:16 UTC by Stan0934

- [DEMO LINK](https://stan0934.github.io/layout_stars/)
- [TEST REPORT LINK](https://stan0934.github.io/layout_stars/report/html_report/)

2022-10-20 18:17 UTC, Stan0934 commented
BACKSTOP ERROR: Reference file not found /Users/konstantinfedosenko/projects/layout_stars/backstop_data/bitmaps_reference/stars--2.png

BACKSTOP ERROR: Reference file not found /Users/konstantinfedosenko/projects/layout_stars/backstop_data/bitmaps_reference/stars--4.png

BACKSTOP ERROR: Reference file not found /Users/konstantinfedosenko/projects/layout_stars/backstop_data/bitmaps_reference/stars--5.png

2022-10-21 15:34 UTC, Stan0934 commented on src/index.html
> +      <div class="stars__star s3"></div>
Removed redundant code

2022-10-21 15:35 UTC, Stan0934 commented on src/style.css
> +}
Should I do it in this task or just get familiar with this function?

2022-10-23 08:25 UTC, polosanya requested changes
Try to delete `bitmaps_reference` folder and `npm i` again
![image](https://user-images.githubusercontent.com/96409563/197382142-8d35d926-2490-4cc0-a217-97743e79f417.png)
If you have any questions, please ask them in fe_chat and tag mentors. It will be faster, because your answers in GitHub will be visible to mentor only after you re-request review 🙂

2022-10-23 14:42 UTC, Stan0934 commented
Thanks for the advice! All tests passed. But on the Mate Academy website it is indicated that the Pull request was rejected

2022-10-24 08:00 UTC, polosanya approved these changes
Good job!

2023-09-07 12:06 UTC, closed without merging