1st commit, html/css built, tests passed
mate-academy/layout_stars pull request #2075
Opened 2022-11-04 10:11 UTC by Sergei-Nikolaienko

2022-11-05 12:08 UTC, AlisaVlasova requested changes

2022-11-05 12:08 UTC, AlisaVlasova commented on src/style.css
> +}
```suggestion
.stars--1 div:nth-child(-n+1),
.stars--2 div:nth-child(-n+2) {
  background-image: url(./images/star-active.svg);
}
```
об'єднай всі через кому

2022-11-06 12:02 UTC, SanyaBratashchuk approved these changes

2022-11-06 12:02 UTC, SanyaBratashchuk commented on src/index.html
> +      <div class="stars__content"></div>
```suggestion
      <div class="stars__star"></div>
```
Fix it everywhere

2023-01-12 09:54 UTC, closed without merging