first commit
mate-academy/layout_stars pull request #2106
Opened 2022-11-07 11:43 UTC by RatiBorRozGa

- [DEMO LINK](https://@RatiBorRozGa.github.io/layout_stars/)
- [TEST REPORT LINK](https://@RatiBorRozGa.github.io/layout_stars/report/html_report/)

2022-11-07 12:52 UTC, stanislav-topikha requested changes
test report link is broken

2022-11-08 09:57 UTC, loralevitska requested changes

2022-11-08 09:57 UTC, loralevitska commented on src/style.css
> +  margin-left: -4px;
it's bad to set negative values, check your classes, you first set the value, and then subtract (instead of subtraction, you can reset to zero)

2022-11-08 09:57 UTC, loralevitska commented on src/style.css
> +.stars--5 :nth-child(-n+5) {
check you tests before review. You have failed tests

```suggestion
.stars--1:nth-child(1),
.stars--2:nth-child(-n+2),
.stars--3:nth-child(-n+3),
.stars--4:nth-child(-n+4),
.stars--5:nth-child(-n+5) {
```

2022-11-08 19:41 UTC, loralevitska reviewed
try to fix the tests, there is no picture of active stars in the tests

![image](https://user-images.githubusercontent.com/70009205/200659457-b78636fb-c495-4f84-ace8-c4655de188c0.png)

2022-11-10 08:04 UTC, closed without merging