Develop
mate-academy/layout_stars pull request #2255
Opened 2022-12-08 21:03 UTC by d-beschastnyi

- [DEMO LINK](https://d-beschastnyi.github.io/layout_stars/)
- [TEST REPORT LINK](https://d-beschastnyi.github.io/layout_stars/report/html_report/)

2022-12-09 12:58 UTC, stanislav-topikha requested changes
Something wrong with your demo
![image](https://user-images.githubusercontent.com/99331793/206707801-823c5cd0-c754-439a-b7c8-a23388111bd7.png)

2022-12-09 15:28 UTC, stanislav-topikha requested changes

2022-12-09 15:28 UTC, stanislav-topikha commented on src/style.css
> +.stars--4 > .stars__star:nth-child(-n+4) {
```suggestion
.stars--5 .stars__star,
.stars--1 .stars__star:first-child,
.stars--2 .stars__star:nth-child(-n+2),
.stars--3 .stars__star:nth-child(-n+3),
.stars--4 .stars__star:nth-child(-n+4) {
```

2022-12-09 15:28 UTC, stanislav-topikha commented on src/style.css
> +}
it’s forbidden to set anything except `box-sizing` inside `*` selector

2022-12-10 10:57 UTC, AlisaVlasova approved these changes

2024-08-06 18:12 UTC, closed without merging