Develop
mate-academy/layout_stars pull request #2280
Opened 2022-12-14 18:31 UTC by maxonshev

2022-12-15 16:43 UTC, UnknownAI requested changes

2022-12-15 16:43 UTC, UnknownAI commented on src/index.html
> +      <div class="stars_star"></div>
for this class name should be two underscores instead of one, please change this everywhere

2022-12-15 16:43 UTC, UnknownAI commented on src/style.css
> +.stars--1 .stars_star:first-child,
not a big mistake, but it is better to have the same structure and use `nth-child` instead `first-child`

2022-12-16 18:43 UTC, ViktorHavryliuk approved these changes

2022-12-17 08:01 UTC, SanyaBratashchuk approved these changes

2025-03-07 10:53 UTC, closed without merging