add stars
mate-academy/layout_stars pull request #2514
Opened 2023-02-16 00:58 UTC by 1v43k

- [DEMO LINK](https://1v43k.github.io/layout_stars/)
- [TEST REPORT LINK](https://1v43k.github.io/layout_stars/report/html_report/)

2023-02-16 13:33 UTC, IvanFesenko requested changes
Check comment

2023-02-16 13:33 UTC, IvanFesenko commented on src/style.css
> +}
You can use comma
```suggestion
.stars--1 :nth-child(-n+1),
.stars--2 :nth-child(-n+2),
.stars--3 :nth-child(-n+3),
.stars--4 :nth-child(-n+4),
.stars--5 :nth-child(-n+5) {
  background-image: var(--active-star);
}
```

2023-02-16 15:56 UTC, 1v43k commented
> Your link isn't work

2023-02-16 20:32 UTC, closed without merging

2023-02-17 10:33 UTC, VitaliyBondarenko1982 reviewed
PR closed.

2023-02-17 10:33 UTC, VitaliyBondarenko1982 commented on src/style.css
> +  margin: 0;
Redundant to make margin: 0 for all selectors.
Make just where it necessary. In this case just for div.

2023-02-17 10:33 UTC, VitaliyBondarenko1982 commented on src/style.css
> +}
Please fix this comment.

2023-02-17 11:31 UTC, 1v43k commented
> PR closed. Why did you close PR?

In this PR my npm module didn't work correctly, since I didn't success to delete and reinstall it, I decided to close it and create a new one  #2522

2023-02-19 13:15 UTC, VitaliyBondarenko1982 commented on src/style.css
> +  margin: 0;
UPD: * just for body