add stars
mate-academy/layout_stars pull request #2602
Opened 2023-02-25 15:12 UTC by 6houston6

2023-02-27 09:17 UTC, polosanya requested changes
Pay attention to the tests. Let's try to delete the backstop_data folder and run npm i and tests again after changes.
Feel free to ask for help in fe_chat if you have any difficulties)

2023-02-27 09:17 UTC, polosanya commented on src/index.html
> +    <div class="stars stars__0">
```suggestion
    <div class="stars stars--0">
```
It's a modifier, not a block element

2023-02-27 09:17 UTC, polosanya commented on src/style.css
> +  margin: 0;
Don't reset margins using * selector. It applies to all the elements, which is not good for performance

2023-02-27 09:17 UTC, polosanya commented on src/style.css
> +  padding: 32px 22px ;
Do you really need these paddings?

2023-02-27 09:17 UTC, polosanya commented on src/style.css
> +}
It's cool that you implemented these styles. but there is nothing about this in task description

2023-02-27 09:17 UTC, polosanya commented on src/style.css
> +}
```suggestion
  margin-right: 4px;
}
```
I'm not sure that last stars should have this margin too
![image](https://user-images.githubusercontent.com/96409563/221522696-50c40020-0b67-459c-ad20-b1ba03c9d040.png)

2023-02-28 09:55 UTC, 6houston6 commented
https://github.com/mate-academy/layout_stars/pull/2602#issue-1599737768
https://6houston6.github.io/layout_stars/report/html_report/

2023-02-28 10:25 UTC, anstsot approved these changes
Great job!

2023-03-24 12:27 UTC, closed without merging