- [DEMO LINK](https://Sleptco.github.io/layout_stars/) - [TEST REPORT LINK](https://Sleptco.github.io/layout_stars/report/html_report/)
mate-academy/layout_stars pull request #2627
Opened 2023-03-03 14:52 UTC by Sleptco

2023-03-03 15:30 UTC, SerhiiKirik requested changes
Well done 🔥 
Let's improve your code & try to pass the tests
Remove the margin-right from the last star
![image](https://user-images.githubusercontent.com/91411692/222760438-5a890d0b-f33a-429d-9b8e-ff308e8444b7.png)

2023-03-03 15:30 UTC, SerhiiKirik commented on .github/workflows/test.yml
> +        path: backstop_data
In the future - Do not add extra files to PR
To add the file to a commit use git add src/.

2023-03-03 15:30 UTC, SerhiiKirik commented on src/style.css
> +  background-repeat: no-repeat;
you already have this in class .stars_star
Remove from all cases
```suggestion
```

2023-03-06 10:08 UTC, Sleptco commented
> Let's improve your code & try to pass the tests



> Well done 🔥 Let's improve your code & try to pass the tests Remove the margin-right from the last star ![image](https://user-images.githubusercontent.com/91411692/222760438-5a890d0b-f33a-429d-9b8e-ff308e8444b7.png)
![image](https://user-images.githubusercontent.com/116346992/223079234-0bb6077e-2f84-4ecd-91ec-9550d536b91c.png)
коли прибираю у останьої зірки марджин, то тест зовсім не проходить.

.stars_star:last-child {
  margin-right: 0;
}

2023-03-06 15:57 UTC, mykhalenych requested changes

2023-03-06 15:57 UTC, mykhalenych commented on src/style.css
> +.stars--5 .stars_star {
```suggestion
.stars--5 .stars_star,
.stars--1 .stars_star:first-child,
... {
  background-image: url("images/star-active.svg");
  }
```

2023-03-07 08:44 UTC, Volodymyr-Melnyk-Fron10der approved these changes
Good, just take a look on one my comment to avoid it in future

2023-03-07 08:44 UTC, Volodymyr-Melnyk-Fron10der commented on src/index.html
> +      <div class="stars stars--0">
don't add extra space btw parent and child node

2024-12-10 08:38 UTC, closed without merging