V_1
mate-academy/layout_stars pull request #2792
Opened 2023-04-12 20:19 UTC by Dima-Kovalskiy

https://<Dima-Kovalskiy>.github.io/layout_stars/
https://<Dima-Kovalskiy>.github.io/layout_stars/report/html_report/

2023-04-13 08:13 UTC, polosanya requested changes
Please add the correct clickable links to the PR description.
Also, make sure that you added all the files from src folder to your commit.
Now only readme file is present on GitHub(

2023-04-13 08:13 UTC, polosanya commented on readme.md
> +- [TEST REPORT LINK](https://<Dima-Kovalskiy>.github.io/layout_stars/report/html_report/)
```suggestion
- [DEMO LINK](https://Dima-Kovalskiy.github.io/layout_stars/)
- [TEST REPORT LINK](https://Dima-Kovalskiy.github.io/layout_stars/report/html_report/)
```

2023-04-14 20:26 UTC, Dima-Kovalskiy commented
> https://.github.io/layout_stars/

2023-04-14 20:26 UTC, closed without merging

2023-04-14 20:28 UTC, Dima-Kovalskiy commented
https://Dima-Kovalskiy.github.io/layout_stars/
https://Dima-Kovalskiy.github.io/layout_stars/report/html_report/