add task solution
mate-academy/layout_stars pull request #2804
Opened 2023-04-16 19:09 UTC by IntensivePro

- [DEMO LINK](https://IntensivePro.github.io/layout_stars/)
- [TEST REPORT LINK](https://IntensivePro.github.io/layout_stars/report/html_report/)

2023-04-17 06:32 UTC, etojeDenys requested changes
almost done

2023-04-17 06:32 UTC, etojeDenys commented on src/index.html
> +    <!-- <h1>Stars</h1> -->
It is not necessary to comment out the 'h1' tag. Removing the comment would make the code cleaner. If you want to keep the 'h1' element, just uncomment it. 📝

2023-04-17 06:32 UTC, etojeDenys commented on src/style.css
> +}
```suggestion
.stars__star:not(:last-child) {
  margin-right: 4px;
}
```

2023-04-22 10:56 UTC, Anastasiia-Svintsova approved these changes

2023-04-22 10:56 UTC, Anastasiia-Svintsova commented on src/index.html
> +      <div class="stars stars--1">
Don't forget to add empty lines between multiline sibling blocks of HTML
```suggestion
      </div>
      
      <div class="stars stars--1">
```

2023-06-10 12:37 UTC, VitaliyBondarenko1982 approved these changes

2023-06-10 12:44 UTC, VitaliyBondarenko1982 approved these changes

2025-07-27 21:41 UTC, closed without merging