add task solution
mate-academy/layout_stars pull request #2879
Opened 2023-04-26 14:30 UTC by MariaSnegireva

- [DEMO LINK](https://MariaSnegireva.github.io/layout_stars/)
- [TEST REPORT LINK](https://MariaSnegireva.github.io/layout_stars/report/html_report/)

2023-04-26 16:02 UTC, Viktor-Kost requested changes

2023-04-26 16:02 UTC, Viktor-Kost commented on src/style.css
> +  background-position: center;
redundant as you've already added these rules to .stars__star
```suggestion
```

2023-04-26 16:02 UTC, Viktor-Kost commented on src/style.css
> +
```suggestion
```

2023-04-26 16:02 UTC, Viktor-Kost commented on src/style.css
> +  background-position: center;
apply background `shorthand`

2023-04-27 11:36 UTC, MariaSnegireva commented on src/style.css
> +  background-position: center;
done

2023-04-27 13:35 UTC, IvanFesenko approved these changes

2023-05-29 12:47 UTC, closed without merging