layout_stars
mate-academy/layout_stars pull request #2893
Opened 2023-05-02 11:15 UTC by SweeeD1

2023-05-02 11:29 UTC, Anastasiia-Svintsova requested changes
- All tests failed 😢 Fix it, please. If you have any questions, feel free to ask them in the chat 
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/99403198/235653478-edd2b915-95cd-429a-b21f-c1fa5b27482d.png">

2023-05-02 11:29 UTC, Anastasiia-Svintsova commented on src/index.html
> +        <div class="stars__star none_active"> </div>
Don't add additional class names to the `stars__star`. It's redundant. You can use a modifier for the stars block and  :nth() child for it
```suggestion
        <div class="stars__star"> </div>
        <div class="stars__star"> </div>
        <div class="stars__star"> </div>
        <div class="stars__star"> </div>
        <div class="stars__star"> </div>
```

2023-05-02 11:29 UTC, Anastasiia-Svintsova commented on src/style.css
> +}
As I said before, use a modifier for the stars block and :nth() child instead of additional classnames

2023-05-09 13:27 UTC, volodymyr-soltys97 commented on readme.md
> +- [TEST REPORT LINK](https://SweeeD1.github.io/layout_stars/report/html_report/)
Add these links as comment here 
![image](https://github.com/mate-academy/layout_stars/assets/64750958/8783510e-4a61-46bd-80ca-66d751f43c0f)

2023-05-09 13:28 UTC, volodymyr-soltys97 commented on src/index.html
> +      <div class="stars__star"></div>
If we have no content, we can use a single tag, but this is optional
```suggestion
      <div class="stars__star" />
```

2023-05-24 11:29 UTC, closed without merging