Developing...
mate-academy/layout_stars pull request #2895
Opened 2023-05-02 16:10 UTC by timohahaaa

https://timohahaaa.github.io/layout_stars/report/html_report/

https://timohahaaa.github.io/layout_stars/

2023-05-02 18:10 UTC, qoa11a requested changes
Almost perfect! One small fix.

2023-05-02 18:10 UTC, qoa11a commented on src/style.css
> +}
You should move it under one selector like this:
`.stars--1 span:first-child, .stars--2 span:nth-child(-n+2), ... { ...styles go here }`

2023-05-03 06:31 UTC, polosanya requested changes
A few small, but important changes left 🙂

2023-05-03 06:31 UTC, polosanya commented on src/style.css
> +.stars--5 span:nth-child(-n+5) {
```suggestion
.stars--1 :first-child,
.stars--2 :nth-child(-n+2),
.stars--3 :nth-child(-n+3),
.stars--4 :nth-child(-n+4),
.stars--5 :nth-child(-n+5) {
```
There is no need to increase the specificity

2023-05-03 06:31 UTC, polosanya commented on src/style.css
> +  background-position: center;
Do you really need to duplicate all styles? Only background image changes, all other properties are the same

2023-05-04 06:29 UTC, polosanya approved these changes
Well done! 🔥

2023-05-23 17:35 UTC, polosanya approved these changes
Super!

2023-06-19 18:57 UTC, qoa11a approved these changes

2024-05-28 07:51 UTC, closed without merging