layout_stars
mate-academy/layout_stars pull request #2961
Opened 2023-05-18 08:30 UTC by DmitryVolchokFE

https://dmitryvolchokfe.github.io/layout_stars/
https://dmitryvolchokfe.github.io/layout_stars/report/html_report/

2023-05-18 11:11 UTC, volodymyr-soltys97 requested changes
Good job
But let's make your code more sophisticated
Let's remove the right indentation for the last elements
![image](https://github.com/mate-academy/layout_stars/assets/64750958/37397a9e-14db-4a24-98cb-47ba3991e331)

2023-05-18 11:11 UTC, volodymyr-soltys97 commented on src/style.css
> +.stars--4 :nth-child(-n + 4),
Change the selector `.stars--4 :nth-child(-n + 4)` to `.stars--4 .stars__star:nth-child(-n + 4)` to target the correct child elements.

2023-05-18 12:07 UTC, nazarmatsevych approved these changes

2023-05-18 12:07 UTC, nazarmatsevych commented on src/style.css
> +}
```suggestion
.stars__star:last-child {
  margin-right: 0;
}
```

Should work as well

2023-05-24 08:28 UTC, DmitryVolchokFE commented
![image](https://github.com/mate-academy/layout_stars/assets/129862088/ff0a1d52-fedc-433e-b3a4-e11042ac5151)
You need to confirm the task again

2023-05-24 10:13 UTC, nazarmatsevych approved these changes
No problem but i think it doesnt help to fix this problem, you have to create new form and new pull request to get this task done

2023-11-15 11:12 UTC, closed without merging