create Layout stars
mate-academy/layout_stars pull request #3021
Opened 2023-05-26 08:53 UTC by KarelVito

2023-05-27 10:10 UTC, SanyaBratashchuk requested changes

2023-05-27 10:10 UTC, SanyaBratashchuk commented on src/style.css
> +  background-image: url(./images/star.svg);
combine selectors with same styles. 
Example `.block1, .block2, .block3 {  color: white;}`

2023-05-27 10:10 UTC, SanyaBratashchuk commented on src/style.css
> +  background-image: url(./images/star.svg);
Set is as default background-image for .stars__star

2023-05-27 13:25 UTC, ivbutsykin approved these changes
Good job!

2023-05-27 13:25 UTC, ivbutsykin commented on readme.md
> +- [TEST REPORT LINK](https://KarelVito.github.io/layout_stars/report/html_report/)
Don't forget add it in description

2023-05-30 07:20 UTC, KarelVito commented
- [DEMO LINK]
- https://KarelVito.github.io/layout_stars/
- [TEST REPORT LINK]
- https://KarelVito.github.io/layout_stars/report/html_report/

2023-05-30 12:30 UTC, SerhiiKirik approved these changes
Sync 🧑‍💻

2023-09-06 17:32 UTC, closed without merging