add task solution
mate-academy/layout_stars pull request #3099
Opened 2023-06-02 02:39 UTC by MaksymKolesnyk

https://MaksymKolesnyk.github.io/layout_stars/
https://MaksymKolesnyk.github.io/layout_stars/report/html_report/

2023-06-02 08:20 UTC, polosanya requested changes
Keep going! Pay attention to the design and task description

2023-06-02 08:20 UTC, polosanya commented on src/index.html
> +        <div class="stars__star stars__star--icon"></div>
```suggestion
      <section class="stars stars--0">
        <div class="stars__star"></div>
        <div class="stars__star"></div>
        <div class="stars__star"></div>
        <div class="stars__star"></div>
        <div class="stars__star"></div>
```
Stars elements shouldn't have any modifiers
![image](https://github.com/mate-academy/layout_stars/assets/96409563/551d0db9-6965-43d7-bc46-ae4b12efd1ea)

2023-06-05 09:14 UTC, OleziO approved these changes

2023-06-05 09:14 UTC, OleziO commented on src/style.css
> +/* #endregion */
Remove all comments

2024-02-05 22:55 UTC, closed without merging