Implemented task and tests
mate-academy/layout_stars pull request #3248
Opened 2023-07-04 17:26 UTC by ekreed

- [DEMO LINK](https://ekreed.github.io/layout_stars/)
- [TEST REPORT LINK](https://ekreed.github.io/layout_stars/report/html_report/)

2023-07-04 18:46 UTC, VitaliyBondarenko1982 requested changes

2023-07-04 18:46 UTC, VitaliyBondarenko1982 commented on src/index.html
> +      <div class="stars__star stars__star--active"></div>
```suggestion
      <div class="stars__star"></div>
```
no need modifier for stars__star 
for amount of active stars should be responsible stars--n modifier

2023-07-04 18:46 UTC, VitaliyBondarenko1982 commented on src/index.html
> +      <div class="stars__star stars__star--active"></div>
```suggestion
      <div class="stars__star"></div>
      <div class="stars__star"></div>
```
same here and for other stars rows

2023-07-04 18:46 UTC, VitaliyBondarenko1982 commented on src/style.css
> +.stars__star--active {
instead modifier for  .stars__star--active modifier use .stars-1 ... .stars-5 modifiers and `:nth-child` pseudo class

2023-07-05 08:20 UTC, OleziO requested changes

2023-07-05 10:34 UTC, volodymyr-soltys97 approved these changes
Nice work 🔥

2024-02-29 17:59 UTC, closed without merging