add task solution
mate-academy/layout_stars pull request #3289
Opened 2023-07-10 14:21 UTC by kabakTech

[DEMO LINK](https://kabaktech.github.io/layout_stars/)
[TEST REPORT LINK](https://kabaktech.github.io/layout_stars/report/html_report/)

it fails the test but works fine. I managed to remove margin-right: 4px;

2023-07-11 11:34 UTC, JoyCoffeeAddict requested changes

2023-07-11 11:34 UTC, JoyCoffeeAddict commented on src/style.css
> +  width: 96px;
If you delete `width` and `justify-content`, then the effect will be almost the same, but this time correct. This is probably causing your problems with tests. Please read checklist again and apply point 3.

2023-07-11 11:34 UTC, JoyCoffeeAddict commented on src/style.css
> +.star__wrapper {
You don't have such class in your html, so this selector is unnecessary.

2023-07-11 11:34 UTC, JoyCoffeeAddict commented on src/style.css
> +.stars__item {
You need to set fixed margin on each start to position them correctly.

2023-07-12 13:51 UTC, kabakTech commented
[DEMO LINK](https://kabaktech.github.io/layout_product-cards/)
[TEST REPORT LINK](https://kabaktech.github.io/layout_product-cards/report/html_report/)

2023-07-13 11:35 UTC, closed without merging