Solution
mate-academy/layout_stars pull request #3505
Opened 2023-08-21 19:26 UTC by katya-sn

- [DEMO LINK](https://katya-sn.github.io/layout_stars/)
- [TEST REPORT LINK](https://katya-sn.github.io/layout_stars/report/html_report/)

2023-08-22 04:11 UTC, mykhalenych requested changes
your links aren't working

2023-08-22 04:11 UTC, mykhalenych commented on src/index.html
> +          <div class="stars__star stars__star--active"></div>
<img width="862" alt="Screenshot 2023-08-22 at 07 10 36" src="https://github.com/mate-academy/layout_stars/assets/53228259/e756aee1-bf02-4e74-82ea-a5c6c8972a83">

missed requirements

2023-08-22 14:21 UTC, katya-sn commented on src/index.html
> +          <div class="stars__star stars__star--active"></div>
я неправильно розумію вимоги -  я додала в кожен з 5ти блоків клас stars--N ?

2023-08-22 14:22 UTC, katya-sn commented on src/index.html
> +          <div class="stars__star stars__star--active"></div>
oops, stars (not star)

2023-08-23 07:29 UTC, volodymyr-soltys97 requested changes
Demo link, you need to make deploy
<img width="847" alt="image" src="https://github.com/mate-academy/layout_stars/assets/64750958/defad066-ed84-4736-8d82-373fe505c4c7">

2023-08-23 07:29 UTC, volodymyr-soltys97 commented on src/index.html
> +          <div class="stars__star stars__star--active"></div>
Need to fix it everywhere
```suggestion
          <div class="stars__star"></div>
          <div class="stars__star"></div>
```

2023-08-23 18:55 UTC, katya-sn commented
https://katya-sn.github.io/layout_stars/

2023-08-24 07:07 UTC, mykhalenych requested changes
your test link isn't working

2023-08-25 17:34 UTC, closed without merging