create stars section
mate-academy/layout_stars pull request #3563
Opened 2023-09-05 13:08 UTC by buffi4ka

https://buffi4ka.github.io/layout_stars/
https://buffi4ka.github.io/layout_stars/report/html_report/

I've been sitting for three hours and can't pass the automated tests. It's a sad statistic. Please help and point out my mistakes.

2023-09-06 10:13 UTC, polosanya requested changes
Nice! Let's try to pass the tests)
If you have any difficulties, please feel free to ask for help in qna chat or sign up for QnA session 🙂

2023-09-06 10:13 UTC, polosanya commented on src/index.html
> +      <div class="container">
Do you really need a container here?

2023-09-06 10:13 UTC, polosanya commented on src/style.css
> +} */
Don't forget to remove the comments

2023-09-06 10:13 UTC, polosanya commented on src/style.css
> +  height: 96px;
![image](https://github.com/mate-academy/layout_stars/assets/96409563/d0f914cc-b02c-41de-aa3c-99b0f78e99e5)

2023-09-06 10:13 UTC, polosanya commented on src/style.css
> +  width: 96px;
The styles are almost the same as for container. You shouldn't set the fixed sizes for it. Set the sizes and margins for stars elements

2023-09-06 14:27 UTC, superpooperxxx requested changes
Hey, seems like you forgot to update gh-pages and tests link.😢 Cannot see the changes

2023-09-06 14:27 UTC, superpooperxxx commented on src/style.css
> +  box-sizing: border-box;
Never reset `margins` and `padding` with *. It takes so much resources. Use `*` only for `box-sizing` properties.

2023-09-06 14:27 UTC, superpooperxxx commented on src/style.css
> +}
Delete what you don't use

2023-09-07 07:54 UTC, superpooperxxx requested changes
Hey, you need to create `develop` branch and create a Pull Request from it to `master`
❌
<img width="712" alt="image" src="https://github.com/mate-academy/layout_stars/assets/49764881/3867dc8a-feb8-4eb4-8013-c4ba4deb66b9">
✅
<img width="670" alt="image" src="https://github.com/mate-academy/layout_stars/assets/49764881/38273e6c-08b0-482c-94b0-3f79550bd56c">

2023-09-07 07:57 UTC, superpooperxxx requested changes
<img width="437" alt="image" src="https://github.com/mate-academy/layout_stars/assets/49764881/92a0a31c-a1c9-4a95-bc69-1bc5bb99f4f7">

2023-09-07 08:37 UTC, closed without merging