stars_1.0
mate-academy/layout_stars pull request #3820
Opened 2023-11-18 19:46 UTC by serjgrm

- [DEMO LINK](https://serjgrm.github.io/layout_stars/)
- [TEST REPORT LINK](https://serjgrm.github.io/layout_stars/report/html_report/)

2023-11-19 08:33 UTC, loralevitska requested changes
Good job! There are things that should be fixed:
- check you tests and try to pass all of them
![image](https://github.com/mate-academy/layout_stars/assets/70009205/9fb984f7-ecb0-4c60-90aa-f4a8a29d7561)

2023-11-19 08:33 UTC, loralevitska commented on src/style.css
> +  background-position: center center;
Combine with [`background` property](https://developer.mozilla.org/en-US/docs/Web/CSS/background)

2023-11-22 09:44 UTC, etojeDenys requested changes

2023-11-22 09:44 UTC, etojeDenys commented on src/style.css
> +}
combine in one selector using the comma

2023-11-22 09:44 UTC, etojeDenys commented on src/style.css
> +}
```suggestion
.stars__star:first-child {
  margin-left: 0;
}

```

2023-11-22 09:44 UTC, etojeDenys commented on src/style.css
> +  margin: 2px;
```suggestion
  margin-left: 4px;
```

2023-11-22 22:30 UTC, closed without merging