solution
mate-academy/layout_stars pull request #3893
Opened 2023-12-05 18:46 UTC by HoTaBu4

- [DEMO LINK](https://HoTaBu4.github.io/layout_stars/)
- [TEST REPORT LINK](https://HoTaBu4.github.io/layout_stars/report/html_report/)

- [x ] Yellow stars are added with container modifier + pseudo-selector (NO extra classes)
- [ x] Each BEM block has its own separate file
- [ x] All `Typical Mistakes` from `BEM` lesson theory are checked.
- [x ] Code follows all the [Code Style Rules ❗️](./checklist.md)

2023-12-05 18:51 UTC, Viktor-Kost requested changes
Also please check your deployment since current links lead to 404 page. If you need any help feel free to ask at fe_chat

2023-12-05 18:51 UTC, Viktor-Kost commented on src/style.css
> +}
```suggestion
.stars--1 .stars__star:nth-child(-1n + 1),
.stars--2 .stars__star:nth-child(-1n + 2),
.stars--3 .stars__star:nth-child(-1n + 3),
.stars--4 .stars__star:nth-child(-1n + 4),
.stars--5 .stars__star:nth-child(n) {
  background-image: url("../src/images/star-active.svg");
}
```

2023-12-05 18:51 UTC, Viktor-Kost commented on src/style.css
> +}
it's not a good practice to use `*` selector for resetting margin. just reset for `body` tag
```suggestion
```

2023-12-05 18:51 UTC, Viktor-Kost commented on src/style.css
> +}
```suggestion
.stars {
  display: flex;
}
```

2023-12-05 18:51 UTC, Viktor-Kost commented on src/style.css
> +}
```suggestion
.stars__star {
  width: 16px;
  height: 16px;
  background-repeat: no-repeat;
  background-image: url("../src/images/star.svg");
  background-position: center;
}
```

2023-12-09 17:34 UTC, closed without merging

2023-12-11 18:52 UTC, HoTaBu4 commented
https://hotabu4.github.io/layout_stars/report/html_report/ [TEST REPORT LINK]
https://hotabu4.github.io/layout_stars/ [DEMO LINK]

2024-01-04 16:01 UTC, VitaliyBondarenko1982 approved these changes
Link for tests not works but code and demo link with implementation looks good.