Develop
mate-academy/layout_stars pull request #3924
Opened 2023-12-13 18:26 UTC by ant-tur

- [DEMO LINK](https://ant-tur.github.io/layout_stars/)
- [TEST REPORT LINK](https://ant-tur.github.io/layout_stars/report/html_report/)

2023-12-13 19:29 UTC, nazarmatsevych requested changes
Good work but let's make some improvements

2023-12-13 19:29 UTC, nazarmatsevych commented on src/index.html
> +
Redundant empty line between parent and child elements

2023-12-13 19:29 UTC, nazarmatsevych commented on src/style.css
> +}
Combine selectors using comma to avoid code duplication,  example below:

.selector1,
.selector2 {
  your styles here...
}

2023-12-14 10:33 UTC, volodymyr-soltys97 requested changes
There are no stars on the page, need to fix it
<img width="1512" alt="image" src="https://github.com/mate-academy/layout_stars/assets/64750958/9ab38fe8-97b7-4963-b421-da93af8569b2">

2023-12-14 10:33 UTC, volodymyr-soltys97 commented on src/index.html
> +    <div class="stars stars--1">
Add a blank line between the block
```suggestion
    </div>
    
    <div class="stars stars--1">
```

2023-12-14 10:33 UTC, volodymyr-soltys97 commented on src/style.css
> +  height: 16px;
No need to duplicate these styles
```suggestion
```

2023-12-14 11:56 UTC, lerastarynets approved these changes
lgtm 🚀

2025-05-18 08:17 UTC, closed without merging