add task solution
mate-academy/layout_stars pull request #4026
Opened 2024-01-15 08:58 UTC by AnatoliiMarushchak

- [x] Yellow stars are added with container modifier + pseudo-selector (NO extra classes)
- [x] Each BEM block has its own separate file
- [x] All `Typical Mistakes` from `BEM` lesson theory are checked.
- [x] Code follows all the [Code Style Rules ❗️](./checklist.md)

2024-01-15 09:02 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's improve your code
Need to remove the margin right for the last star
<img width="377" alt="image" src="https://github.com/mate-academy/layout_stars/assets/64750958/db2e27d2-e3dc-4eae-bea3-b67ae8720b57">

2024-01-15 09:02 UTC, volodymyr-soltys97 commented on src/style.css
> +}
These selectors must be separated by a comma.

2024-01-15 09:41 UTC, AnatoliiMarushchak reviewed
Fixed a bug, improved the code.

2024-01-18 09:10 UTC, etojeDenys approved these changes
lgtm

2024-07-03 11:57 UTC, closed without merging