add solution to stars problem
mate-academy/layout_stars pull request #4225
Opened 2024-03-03 12:12 UTC by vinasxz

- [DEMO LINK](https://vinasxz.github.io/layout_stars/)
- [TEST REPORT LINK](https://vinasxz.github.io/layout_stars/report/html_report/)

Checklist:
- [x] Yellow stars are added with container modifier + pseudo-selector (NO extra classes)
- [x] Each BEM block has its own separate file
- [x] All `Typical Mistakes` from `BEM` lesson theory are checked.
- [x] Code follows all the [Code Style Rules ❗️](./checklist.md)

2024-03-04 19:43 UTC, pedro-ruas requested changes
Your work is very good, the only issue is the missing empty lines between siblings  (between every stars--N and the next one), you can check [Code Style Rules](https://github.com/mate-academy/layout_stars/blob/master/checklist.md).

2024-03-04 19:43 UTC, pedro-ruas commented on src/index.html
> +    </div>
You missed empty lines between sibling blocks (between every stars--N and the next one), you can check [Code Style Rules](https://github.com/mate-academy/layout_stars/blob/master/checklist.md).

2024-03-05 15:57 UTC, jv-aquino approved these changes
Amazing job! Clean code overall and just the right amount of CSS to make everything work!

2024-03-05 15:57 UTC, jv-aquino commented on src/index.html
> +
some unnecessary space here

2024-03-05 15:57 UTC, jv-aquino commented on src/index.html
> +
and here

2024-06-07 19:46 UTC, closed without merging