Add task solution
mate-academy/layout_stars pull request #4256
Opened 2024-03-09 04:19 UTC by Victor-Mirandas

- [DEMO LINK](https://Victor-Mirandas.github.io/layout_stars/)
- [TEST REPORT LINK](https://Victor-Mirandas.github.io/layout_stars/report/html_report/)

2024-03-09 12:30 UTC, Viktor-Kost requested changes

2024-03-09 12:30 UTC, Viktor-Kost commented on readme.md
> +- [TEST REPORT LINK](https://Victor-Mirandas.github.io/layout_stars/report/html_report/)
check your deployment (or ask for a help at fe_chat) since DEMO link leads to readme.md file (not working page), TEST link leads to 404 page

2024-03-09 12:30 UTC, Viktor-Kost commented on src/images/scan272.jpg
Redundant image))

2024-03-09 12:30 UTC, Viktor-Kost commented on src/index.html
> +  <body class="page__body">
no needs to add a class selector to a body since you have only one body on the page

2024-03-09 12:30 UTC, Viktor-Kost commented on src/style.css
> +.page__body {
```suggestion
body {
```

2024-03-09 12:30 UTC, Viktor-Kost commented on src/style.css
> +}
```suggestion
.stars--1 .stars__star:first-child,
.stars--2 .stars__star:nth-child(-n+2),
.stars--3 .stars__star:nth-child(-n+3),
.stars--4 .stars__star:nth-child(-n+4),
.stars--5 .stars__star:nth-child(n) {
  background-image: url(/src/images/star-active.svg);
}
```

2024-03-09 12:30 UTC, Viktor-Kost commented on src/style.css
> +}
you can use  `:not(:last-child)` instead
```suggestion
  background-image: url(/src/images/star.svg);
  background-repeat: no-repeat;
  background-position: center;
}

.stars__star:not(:last-child) {
  margin-right: 4px;
}
```

2024-03-09 12:30 UTC, Viktor-Kost commented on src/index.html
> +    <div class="stars-block stars--0">
```suggestion
    <div class="stars stars--0">
```

2024-03-12 01:48 UTC, closed without merging

2024-03-13 02:43 UTC, Victor-Mirandas commented
- [DEMO LINK](https://Victor-Mirandas.github.io/layout_stars/)
- [TEST REPORT LINK](https://Victor-Mirandas.github.io/layout_stars/report/html_report/)