add task solution
mate-academy/layout_stars pull request #4524
Opened 2024-06-04 20:20 UTC by Mazurok001

- [DEMO LINK](https://Mazurok001.github.io/layout_stars/)
- [TEST REPORT LINK](https://Mazurok001.github.io/layout_stars/report/html_report/)

- [x] Yellow stars are added with container modifier + pseudo-selector (NO extra classes)
- [x] Each BEM block has its own separate file
- [x] All `Typical Mistakes` from `BEM` lesson theory are checked.
- [x] Code follows all the [Code Style Rules ❗️](./checklist.md)

2024-06-05 20:37 UTC, DanilWeda requested changes
Good job.
Check some small comments that i left!
Many thanks)

2024-06-05 20:37 UTC, DanilWeda commented on src/style.css
> +}
You can try use scss loop for this opetrations. 
Try it!

2024-06-05 20:37 UTC, DanilWeda commented on src/style.css
> +} */
remove commented if you don't need it

2024-06-06 10:02 UTC, closed without merging

2024-06-06 10:10 UTC, Mazurok001 reviewed
remove commented

2024-06-06 15:18 UTC, DanilWeda approved these changes
Great! 
Approved! 
Thanks)