add task solution
mate-academy/layout_stars pull request #4554
Opened 2024-06-15 12:45 UTC by Stanenko

- [DEMO LINK](https://Stanenko.github.io/layout_stars/)
- [TEST REPORT LINK](https://Stanenko.github.io/layout_stars/report/html_report/)

2024-06-15 16:05 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's make your code better

2024-06-15 16:05 UTC, volodymyr-soltys97 commented on src/style.css
> +}
These selectors must be separated by commas

2024-06-15 16:05 UTC, volodymyr-soltys97 commented on src/style.css
> +  background-image: url(../src/images/star.svg);
```suggestion
  background-image: url(./images/star.svg);
```

2024-06-15 16:05 UTC, volodymyr-soltys97 commented on src/style.css
> +  background-image: url('../src/images/star-active.svg');
```suggestion
  background-image: url('./images/star-active.svg');
```

2024-07-03 13:09 UTC, anastasiiavorobiova commented on src/style.css
> +.stars__star:nth-child(-n + 1) {
```suggestion
.stars__star:nth-child(-n + 1),
stars--2,
.stars__star:nth-child(-n + 2) ,
.... {
```
Consider grouping your selectors with commas

2024-07-03 14:43 UTC, closed without merging