add solution
mate-academy/layout_stars pull request #4603
Opened 2024-06-24 13:16 UTC by TYaroslav20

- [DEMO LINK](https://TYaroslav20.github.io/layout_stars/)
- [TEST REPORT LINK](https://TYaroslav20.github.io/layout_stars/report/html_report/)

2024-08-06 18:43 UTC, Moroz-Dmytro requested changes
Good work 👍 
But let's make it perfect

2024-08-06 18:46 UTC, Moroz-Dmytro requested changes
Check comments above

2024-08-08 07:00 UTC, Moroz-Dmytro requested changes
Good work, but fix my comments above 😉

2024-08-10 14:25 UTC, VenomMB requested changes
Check comments above

2024-08-10 14:26 UTC, VenomMB requested changes
Check comments above

2024-08-11 10:09 UTC, BudnikOleksii requested changes
.

2024-08-12 11:14 UTC, Moroz-Dmytro requested changes
Comments above

2024-09-09 10:25 UTC, igorkruz requested changes
Check comments above

2025-02-24 12:49 UTC, closed without merging