Develop
mate-academy/layout_stars pull request #488
Opened 2021-05-04 17:00 UTC by dmitriy-tverdokhlibov

2021-05-05 13:30 UTC, vkryvytskyy requested changes

2021-05-05 13:30 UTC, vkryvytskyy commented on src/style.css
> +}
Все повторяющиеся стили вынеси в просто `.stars__star`, а через nth-child устанавливай активную картинку на нужные

2021-05-05 18:00 UTC, dmitriy-tverdokhlibov commented on src/style.css
> +}
Хорошо спсасибо. А почему так лучше? Меньше кода?

2021-05-06 10:48 UTC, vkryvytskyy commented on src/style.css
> +}
Да

2021-05-06 10:49 UTC, vkryvytskyy requested changes

2021-05-06 10:49 UTC, vkryvytskyy commented on src/style.css
> +}
Напиши эти стили через запятую, это же одно и то же правило

2021-05-07 10:07 UTC, vkryvytskyy approved these changes

2025-04-23 19:01 UTC, closed without merging