Solution
mate-academy/layout_stars pull request #649
Opened 2021-07-20 13:57 UTC by b0hdan1

[DEMO LINK](https://b0hdan1.github.io/layout_stars/)

2021-07-21 11:41 UTC, vkryvytskyy requested changes

2021-07-21 11:41 UTC, vkryvytskyy commented on readme.md
> +- [TEST REPORT LINK](https://b0hdan1.github.io/layout_stars/report/html_report/)
Ссылка на тесты не работает, локально тесты запускаются? Если да - покажи скриншот

2021-07-21 11:41 UTC, vkryvytskyy commented on src/style.css
> +  border: 2px solid black;
Это лишнее, не надо ограничивать ширину контейнера и задавать ему border

2021-07-21 11:41 UTC, vkryvytskyy commented on src/style.css
> +}
Напиши эти стили через запятую,

2021-07-23 18:55 UTC, b0hdan1 commented on readme.md
> +- [TEST REPORT LINK](https://b0hdan1.github.io/layout_stars/report/html_report/)
нет, ни в одном задании.

2021-07-26 12:47 UTC, mykola-yarchuk approved these changes

2021-07-26 12:47 UTC, mykola-yarchuk commented on readme.md
> +- [TEST REPORT LINK](https://b0hdan1.github.io/layout_stars/report/html_report/)
для того щоб тести працювали потрібно щоб саме завдання було запущене у сусідньому терміналі і на правильному порті, спробуй

2024-04-25 17:12 UTC, closed without merging