task done
mate-academy/layout_stars pull request #943
Opened 2021-12-22 19:54 UTC by maksym-mishchanchuk

In my opinion, the task is done correctly, but there is a problem with the test. Please look

- [DEMO LINK](https://maksym-mishchanchuk.github.io/layout_stars/)
- [TEST REPORT LINK](https://maksym-mishchanchuk.github.io/layout_stars/report/html_report/)

2021-12-23 08:38 UTC, Anna-Tkachenko requested changes

2021-12-23 08:38 UTC, Anna-Tkachenko commented on src/index.html
> +      </div>
```suggestion
      <div class="starts stars--0">
        <div class="stars__star"></div>
        <div class="stars__star"></div>
        <div class="stars__star"></div>
        <div class="stars__star"></div>
        <div class="stars__star"></div>
      </div>
```

2021-12-23 08:38 UTC, Anna-Tkachenko commented on src/style.css
> +}
Check point 2 in [checklist](https://github.com/mate-academy/layout_stars/blob/master/checklist.md)

2021-12-23 20:49 UTC, Anna-Tkachenko requested changes

2021-12-23 20:49 UTC, Anna-Tkachenko commented on src/style.css
> +}
```suggestion
.stars {
  display: flex;
}
```

2021-12-23 20:49 UTC, Anna-Tkachenko commented on src/style.css
> +  width: 16px;
set margin-right for each star except the last

2021-12-23 20:49 UTC, Anna-Tkachenko commented on src/style.css
> +  background-position: center;
Check 2 point in checklist

2021-12-28 11:11 UTC, OleksiiBlezniuk requested changes

2021-12-28 11:11 UTC, OleksiiBlezniuk commented on src/style.css
> +}
Не исправил, посмотри 2-ой пункт в чеклисте

2021-12-28 13:40 UTC, OleksiiBlezniuk approved these changes
Good job! 🚀

2023-07-07 12:16 UTC, closed without merging