xing xing
mate-academy/layout_stars pull request #972
Opened 2022-01-04 20:35 UTC by Havrysh

- [DEMO LINK](https:/Havrysh.github.io/layout_stars/)
- [TEST REPORT LINK](https://Havrysh.github.io/layout_stars/report/html_report/)

2022-01-04 20:40 UTC, Havrysh commented
<img width="1440" alt="Screen Shot 2022-01-04 at 10 39 31 PM" src="https://user-images.githubusercontent.com/21238164/148121169-f5548de4-cffc-4a87-ae3c-0bac21259dab.png">
<img width="1440" alt="Screen Shot 2022-01-04 at 10 39 24 PM" src="https://user-images.githubusercontent.com/21238164/148121173-0736e8ea-341b-4138-8e8d-6e464973e072.png">

2022-01-05 12:28 UTC, varseniuk requested changes
Давай сильно спростимо код

2022-01-05 12:28 UTC, varseniuk commented on src/style.css
> +  background-position: center;
```suggestion
  background-repeat: no-repeat;
  background-position: center;
```
Дуже багато дублювання. Ці два властивості потрібно додати до .stars__star, адже вони стосуються всіх зірок, і більше ніде не писати

2022-01-05 12:28 UTC, varseniuk commented on src/style.css
> +}
```suggestion
.stars--3 > .stars--star:nth-child(-n+3) {
  background-image: url(images/star-active.svg);
}
```
Це все можна спростити, використавши ось такий селектор. Тобто для всіх nth-child по третій включно буде застосовано бекграунд-імедж із зображенням активної зірки.

А для .stars--star по дефолту додай зображення неактивної зірки

2022-01-05 12:28 UTC, varseniuk commented on src/style.css
> +  border-radius: 0.5px;
```suggestion
```
Це лишнє

2022-01-05 17:10 UTC, vkryvytskyy requested changes

2022-01-05 17:10 UTC, vkryvytskyy commented on src/style.css
> +}
Тут можно одним селектором это написать, так же как ты делаешь это для первых трех дальше

2022-01-05 17:10 UTC, vkryvytskyy commented on src/style.css
> +}
Все это можно написать через запятую

2022-01-06 11:02 UTC, varseniuk approved these changes

2024-12-11 13:41 UTC, closed without merging