Done task Stars
mate-academy/layout_stars pull request #985
Opened 2022-01-16 18:02 UTC by valdesin

Вроде норм но тесты не проходит

2022-01-17 17:13 UTC, vkryvytskyy requested changes

2022-01-17 17:13 UTC, vkryvytskyy commented on src/style.css
> +.stars__star {
![image](https://user-images.githubusercontent.com/38065883/149812626-2f8b8633-6d3b-4307-b38d-f184eef60aab.png)
Отступ между звездочками 4px

2022-01-17 17:13 UTC, vkryvytskyy commented on src/style.css
> +}
Зачем это?

2022-01-17 17:13 UTC, vkryvytskyy commented on src/style.css
> +  margin-left: 3px;
Зачем этот отступ?

2022-01-17 17:13 UTC, vkryvytskyy commented on src/style.css
> +}
Выглядит как дупликация кода, уверен можно сделать без этого, описав только один такой блок

2022-01-22 13:20 UTC, valdesin commented on src/style.css
> +}
Ок, дякую виправив

2022-01-24 12:44 UTC, aliceblunt8 submitted a review, later dismissed
add demo link and test link to the PR

2022-01-31 11:08 UTC, vkryvytskyy requested changes

2022-01-31 11:08 UTC, vkryvytskyy commented on readme.md
> +- [TEST REPORT LINK](https://valdesin.github.io/layout_stars/report/html_report/)
Привет, ссылки не работают, ты делал `npm run deploy`? Если во время выполнения этой команды возникают какие-то ошибки - пиши в fe_chat

2022-01-31 18:21 UTC, valdesin commented on readme.md
> +- [TEST REPORT LINK](https://valdesin.github.io/layout_stars/report/html_report/)
Привет !
Сделал

2022-02-01 12:39 UTC, vkryvytskyy approved these changes

2022-03-04 18:09 UTC, closed without merging